import board

PIN_NEOPIXEL = board.GP22

PIN_COLOUR_SCL = board.GP19
PIN_COLOUR_SDA = board.GP18

PIN_SERVO = board.GP11

PIN_STEPPER_1 = board.GP12
PIN_STEPPER_2 = board.GP13
PIN_STEPPER_3 = board.GP14
PIN_STEPPER_4 = board.GP15

PIN_BACKSWITCH = board.GP21
PIN_FRONTSWITCH = board.GP20



PIN_LIGHTSENSOR = board.GP28_A2
PIN_MOISTURESENSOR = board.GP27_A1